# Generated by Django 3.2.12 on 2023-06-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dane_statusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaj_sekcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja_pliku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ojca_pliku', models.IntegerField(default=0)),
                ('opcjonalna_nazwa', models.CharField(default='', max_length=50)),
                ('opcjonalny_opis', models.TextField(default='')),
                ('data_utworzenia', models.DateField(auto_now=True)),
                ('znacznik_dostepnosci', models.BooleanField(default=True)),
                ('poczatek_sekcji', models.IntegerField(default=0)),
                ('koniec_sekcji', models.IntegerField(default=0)),
                ('rodzaj_sekcji', models.IntegerField(default=0)),
                ('status_sekcji', models.IntegerField(default=0)),
                ('dane_statusu', models.IntegerField(default=0)),
                ('tresc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_sekcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=10)),
                ('tresc', models.TextField(default='')),
                ('rodzic', models.IntegerField(default=0)),
                ('opcjonalny_opis', models.TextField()),
                ('data_utworzenia', models.DateField(auto_now=True)),
                ('znacznik_dostepnosci', models.BooleanField(default=True)),
                ('data_zmiany_znacznika', models.DateField(auto_now=True)),
                ('data_ostatniej_zmiany_zawartosci', models.DateField(auto_now=True)),
                ('wlasciciel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzic', models.IntegerField(default=0)),
                ('nazwa', models.CharField(max_length=20)),
                ('opcjonalny_opis', models.TextField(blank=True, default='')),
                ('data_utworzenia', models.DateTimeField(auto_now=True)),
                ('znacznik_dostepnosci', models.BooleanField(default=True)),
                ('data_zmiany_znacznika', models.DateTimeField(auto_now=True)),
                ('data_ostatniej_zmiany_zawartosci', models.DateTimeField(auto_now=True)),
                ('wlasciciel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
